---
- name: install elasticsearch
  hosts: elasticsearch
  become: yes

  tasks:
  
# На момент сдачи работы ключ перестал скачиваться из-за блокировки. Решение ниже.

  # - name: import the elastic apt key
  #   ansible.builtin.apt_key:
  #     url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
  #     state: present

# Скаченыный файл с ключом копируется на вм и добавляется.
  - name: copy key file
    copy:
      src=/home/admin/ansible/gpg_key
      dest=/home/admin/gpg_key

  - name: add elastik apt key
    ansible.builtin.apt_key:
      file: /home/admin/gpg_key
      state: present

  - name: install elastic repository
    ansible.builtin.apt_repository:
      repo: deb https://mirror.yandex.ru/mirrors/elastic/8/ stable main
      state: present

  - name: update cache repository
    ansible.builtin.apt:
      update_cache: yes

  - name: install packages
    ansible.builtin.apt:
      name:
        - apt-transport-https
        - openjdk-8-jre-headless
        - elasticsearch
      state: present

  - name: setting elasticsearch
    ansible.builtin.lineinfile:
      path: /etc/elasticsearch/elasticsearch.yml
      regexp: "^#network.host: 192.168.0.1"
      line: "network.host: 0.0.0.0"

  - name: enable and restart elastic
    ansible.builtin.systemd:
      name: elasticsearch
      enabled: true
      daemon_reload: true
      masked: no
      state: started

  - name: save authentification pass
    expect:
      command: /usr/share/elasticsearch/bin/elasticsearch-reset-password -u elastic
      responses:
        'Please confirm that you would like to continue' : 'y'
    register: elkpass_result

  - name: output authentification pass
    debug: var=elkpass_result.stdout_lines

  - name: save token to kibana
    ansible.builtin.shell: /usr/share/elasticsearch/bin/elasticsearch-create-enrollment-token -s kibana
    register: token_result

  - name: output token to kibana
    debug: var=token_result.stdout_lines
...