---
- name: install filebeat
  hosts: web_servers
  become: yes

  tasks:
  
 # На момент сдачи работы ключ перестал скачиваться из-за блокировки. Решение ниже.

  # - name: import the elastic apt key
  #   ansible.builtin.apt_key:
  #     url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
  #     state: present

# Скаченыный файл с ключом копируется на вм и добавляется.
  - name: copy key file
    copy:
      src=/home/admin/ansible/gpg_key
      dest=/home/admin/gpg_key

  - name: add elastik apt key
    ansible.builtin.apt_key:
      file: /home/admin/gpg_key
      state: present

  - name: install elastic repository
    ansible.builtin.apt_repository:
      repo: deb https://mirror.yandex.ru/mirrors/elastic/8/ stable main
      state: present

  - name: update cache repository
    ansible.builtin.apt:
      update_cache: yes

  - name: install filebeat
    ansible.builtin.apt:
      name: filebeat
      state: present

  - name: enter elastic password in confiig file filebeat
    ansible.builtin.pause:
      prompt: "Open file ./filebeat_conf/filebeat.yml and insert password"

  - name: copy conf file
    copy: 
      src: ./filebeat_conf/filebeat.yml 
      dest: /etc/filebeat/filebeat.yml 
      mode: 0644
      owner: root
      group: root

  - name: enable and restart filebeat
    ansible.builtin.systemd:
      name: filebeat
      enabled: true
      masked: no
      daemon_reload: true
      state: restarted
...